export const careTags = [
  "Gender-affirming hormone therapy (HRT)",
  "Gender-affirming surgery referrals",
  "PrEP / HIV prevention & treatment",
  "STI screening & sexual health",
  "Mental health & counseling",
  "Family planning / fertility preservation",
  "Legal name & gender marker support",
  "Youth & adolescent care",
  "General primary care (LGBTQ+-affirming)"
];

export const physicianSpecialties = [
  "PRIMARY CARE",
  "THERAPIST",
  "PSYCHIATRIST",
  "OB GYN",
  "HORMONE CARE",
  "URGENT CARE"
];

export const insuranceOptions = [
  "Medical",
  "Covered CA",
  "Medicare",
  "Kaiser",
  "Blue Shield",
  "Uninsured/Self-Pay"
];

export const languageOptions = ["English", "Spanish", "Chinese"];

export const seedProviders = [
  {
    source_id: "seed-liz-cretti-olson",
    name: "Liz Cretti Olson",
    short_summary: "LGBTQ+-affirming clinician focused on sexual health and gender-affirming care.",
    place_name: "Davis Sexual Health Clinic",
    address: "Davis Sexual Health Clinic, Davis, CA",
    city: "Davis",
    state: "CA",
    latitude: 38.5449,
    longitude: -121.7405,
    insurance: ["Medical", "Covered CA", "Uninsured/Self-Pay"],
    specialty: "HORMONE CARE",
    rating: 4.7,
    review_count: 31,
    accepting_patients: true,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "PrEP / HIV prevention & treatment",
      "STI screening & sexual health",
      "Mental health & counseling",
      "Family planning / fertility preservation",
      "Youth & adolescent care"
    ],
    languages: ["English", "Spanish"]
  },
  {
    source_id: "seed-chris-swales",
    name: "Chris Swales",
    short_summary: "Primary care clinician supporting trans and nonbinary hormone care.",
    place_name: "Woodland Clinic Medical Group",
    address: "Woodland Clinic Medical Group, Woodland, CA",
    city: "Woodland",
    state: "CA",
    latitude: 38.6785,
    longitude: -121.7733,
    insurance: ["Medical", "Blue Shield"],
    specialty: "PRIMARY CARE",
    rating: 4.5,
    review_count: 18,
    accepting_patients: false,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "Gender-affirming surgery referrals",
      "PrEP / HIV prevention & treatment",
      "Mental health & counseling",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English"]
  },
  {
    source_id: "seed-brea-bondi-boyd",
    name: "Brea Bondi Boyd",
    short_summary: "Gender-affirming care and reproductive health provider in a larger care system.",
    place_name: "Kaiser Permanente",
    address: "Kaiser Permanente, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5985,
    longitude: -121.391,
    insurance: ["Kaiser", "Medicare", "Covered CA"],
    specialty: "OB GYN",
    rating: 4.8,
    review_count: 42,
    accepting_patients: true,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "Gender-affirming surgery referrals",
      "STI screening & sexual health",
      "Family planning / fertility preservation",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Chinese"]
  },
  {
    source_id: "seed-jenna-whippen",
    name: "Jenna Whippen",
    short_summary: "Trauma-informed provider offering affirming primary care and counseling support.",
    place_name: "One Community Health",
    address: "One Community Health, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.571,
    longitude: -121.503,
    insurance: ["Medical", "Medicare", "Uninsured/Self-Pay"],
    specialty: "THERAPIST",
    rating: 4.9,
    review_count: 27,
    accepting_patients: true,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "PrEP / HIV prevention & treatment",
      "STI screening & sexual health",
      "Mental health & counseling",
      "Legal name & gender marker support",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Spanish"]
  },
  {
    source_id: "seed-ryan-spielvogel",
    name: "Ryan Spielvogel",
    short_summary: "OB-GYN and family medicine clinician with trans and nonbinary health experience.",
    place_name: "Sutter Family Medicine Residency Program",
    address: "Sutter Family Medicine Residency Program, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5702,
    longitude: -121.4689,
    insurance: ["Blue Shield", "Covered CA"],
    specialty: "OB GYN",
    rating: 4.4,
    review_count: 16,
    accepting_patients: false,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "Gender-affirming surgery referrals",
      "Family planning / fertility preservation",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)",
      "STI screening & sexual health"
    ],
    languages: ["English"]
  },
  {
    source_id: "seed-amara-patel",
    name: "Amara Patel",
    short_summary: "Psychiatrist supporting mental health, letters, and care coordination.",
    place_name: "Sacramento Gender Health Center",
    address: "Sacramento Gender Health Center, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5816,
    longitude: -121.4944,
    insurance: ["Medical", "Uninsured/Self-Pay"],
    specialty: "PSYCHIATRIST",
    rating: 4.6,
    review_count: 22,
    accepting_patients: true,
    tags: [
      "Gender-affirming surgery referrals",
      "Mental health & counseling",
      "Legal name & gender marker support",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)",
      "Gender-affirming hormone therapy (HRT)"
    ],
    languages: ["English", "Chinese"]
  },
  {
    source_id: "seed-marisol-reyes",
    name: "Marisol Reyes",
    short_summary: "Urgent and preventive care clinician with harm-reduction experience.",
    place_name: "Davis Community Clinic",
    address: "Davis Community Clinic, Davis, CA",
    city: "Davis",
    state: "CA",
    latitude: 38.5562,
    longitude: -121.747,
    insurance: ["Medical", "Medicare", "Uninsured/Self-Pay"],
    specialty: "URGENT CARE",
    rating: 4.3,
    review_count: 14,
    accepting_patients: true,
    tags: [
      "PrEP / HIV prevention & treatment",
      "STI screening & sexual health",
      "Mental health & counseling",
      "Family planning / fertility preservation",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Spanish"]
  },
  {
    source_id: "seed-noah-kim",
    name: "Noah Kim",
    short_summary: "Youth-centered therapist for LGBTQ+ adolescents and families.",
    place_name: "Yolo Youth Wellness",
    address: "Yolo Youth Wellness, Davis, CA",
    city: "Davis",
    state: "CA",
    latitude: 38.5481,
    longitude: -121.7602,
    insurance: ["Covered CA", "Blue Shield"],
    specialty: "THERAPIST",
    rating: 4.7,
    review_count: 19,
    accepting_patients: false,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "Mental health & counseling",
      "Family planning / fertility preservation",
      "Legal name & gender marker support",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Chinese"]
  },
  {
    source_id: "seed-elena-nguyen",
    name: "Elena Nguyen",
    short_summary: "Primary care physician coordinating HRT, PrEP, and preventive care.",
    place_name: "Midtown Inclusive Health",
    address: "Midtown Inclusive Health, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5759,
    longitude: -121.478,
    insurance: ["Covered CA", "Blue Shield", "Medical"],
    specialty: "PRIMARY CARE",
    rating: 4.6,
    review_count: 24,
    accepting_patients: true,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "PrEP / HIV prevention & treatment",
      "STI screening & sexual health",
      "Mental health & counseling",
      "Family planning / fertility preservation",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Chinese"]
  },
  {
    source_id: "seed-mateo-rivera",
    name: "Mateo Rivera",
    short_summary: "Spanish-speaking therapist supporting LGBTQ+ youth and families.",
    place_name: "River City Counseling",
    address: "River City Counseling, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5882,
    longitude: -121.5056,
    insurance: ["Medical", "Uninsured/Self-Pay"],
    specialty: "THERAPIST",
    rating: 4.9,
    review_count: 36,
    accepting_patients: true,
    tags: [
      "Gender-affirming surgery referrals",
      "Mental health & counseling",
      "Legal name & gender marker support",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)",
      "Gender-affirming hormone therapy (HRT)"
    ],
    languages: ["English", "Spanish"]
  },
  {
    source_id: "seed-hannah-park",
    name: "Hannah Park",
    short_summary: "Psychiatrist for medication support, letters, and care planning.",
    place_name: "Capitol Psychiatry Group",
    address: "Capitol Psychiatry Group, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5797,
    longitude: -121.4891,
    insurance: ["Medicare", "Blue Shield"],
    specialty: "PSYCHIATRIST",
    rating: 4.4,
    review_count: 20,
    accepting_patients: false,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "Gender-affirming surgery referrals",
      "Mental health & counseling",
      "Legal name & gender marker support",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Chinese"]
  },
  {
    source_id: "seed-olivia-chen",
    name: "Olivia Chen",
    short_summary: "OB-GYN offering reproductive health and affirming referral support.",
    place_name: "Sacramento Reproductive Care",
    address: "Sacramento Reproductive Care, Sacramento, CA",
    city: "Sacramento",
    state: "CA",
    latitude: 38.5525,
    longitude: -121.4568,
    insurance: ["Covered CA", "Kaiser", "Blue Shield"],
    specialty: "OB GYN",
    rating: 4.5,
    review_count: 29,
    accepting_patients: true,
    tags: [
      "Gender-affirming hormone therapy (HRT)",
      "Gender-affirming surgery referrals",
      "STI screening & sexual health",
      "Family planning / fertility preservation",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Chinese"]
  },
  {
    source_id: "seed-jordan-brooks",
    name: "Jordan Brooks",
    short_summary: "Urgent care clinician for sexual health, PrEP labs, and referrals.",
    place_name: "Davis Same Day Health",
    address: "Davis Same Day Health, Davis, CA",
    city: "Davis",
    state: "CA",
    latitude: 38.5368,
    longitude: -121.7541,
    insurance: ["Medical", "Medicare", "Uninsured/Self-Pay"],
    specialty: "URGENT CARE",
    rating: 4.2,
    review_count: 12,
    accepting_patients: true,
    tags: [
      "PrEP / HIV prevention & treatment",
      "STI screening & sexual health",
      "Mental health & counseling",
      "Family planning / fertility preservation",
      "Youth & adolescent care",
      "General primary care (LGBTQ+-affirming)"
    ],
    languages: ["English", "Spanish"]
  }
];
